---
title: "About"
output: 
  html_document:
    toc: true
    toc_float: true
---
<br>

## The Project

This project was created as a deliverable for the course POPF P8633 - Issues in School-Based Health in the Heilbrunn Department of Population and Family Health at Columbia University Mailman School of Public Health. 

Our deliverable consists of 3 parts:

* **Part I** - Getting Through Grief: A Guide for Educators
* **Part II** - Getting Through Grief: A Guide for the Classroom
* **Part III** - COVID-19 Resource Guide: Mental Health and Food Assistance Services

<br>

## The Course

**POPF P8633 - Issues in School Based Health** <br>

From the syllabus: "Issues in School Based Health is a course designed to give students the opportunity to engage with schools so that they have experience and they can learn how to apply both theory and practice. A principle of school health is breaking down silos between health and education. Our goal is to provide participants with an opportunity to gain hands-on experience working with NYC public schools. They must complete a project designed to inform the school health-related work at NYC schools in groups. Every year students focus on a topic impacting schools. This year’s focus was staff and teacher mental health support and burnout prevention."

<br>

**Final Project Description: Supporting Teacher Well-Being and Mental Health** <br>

Educators are leaving the field at alarming rates due to burnout and stress. There are additional stressors for teachers of color and COVID and the racial events of 2020 have further compounded teacher stress and trauma. Educator attrition has a negative impact on student learning and the bottom line for schools and school districts. Schools cannot address learning loss if they do not prioritize teacher healing now. As MPH students in this class, we worked in a group to develop a project that supports the needs of the schools related to teacher mental health and well-being.

Specifically, our team:

* Delivered a needs and assets assessment to the school staff (_conversational interview with Brooke Borg from Counseling in Schools -- thank you Brooke for your amazing insight!_)
* Compiled results and worked with schools to come up with a project that would support the need of
the schools (_addressing how to deal with grief in the classroom, which has been exacerbated by COVID_)
* Created an agreed upon deliverable that addresses the problem and present it in a way that
makes sense for teachers and school administrators (_our final 3-part guide_)

<br> 

## The Team

We are a team of MPH candidates in the Heilbrunn Department of Population and Family Health at Columbia University Mailman School of Public Health. 

Please feel free to email us with any questions!

**Jodi Scharf** <br>
Email: [jys2137@cumc.columbia.edu](mailto:jys2137@columbia.edu)  

**Mary Alex Bowen** <br>
Email: [mab2412@cumc.columbia.edu](mailto:mab2412@cumc.columbia.edu)  

**Uriel De Monteverde** <br>
Email: [udd2001@cumc.columbia.edu](mailto:udd2001@cumc.columbia.edu)

**Lauren Kenney** <br>
Email: [lak2195@cumc.columbia.edu](mailto:lak2195@cumc.columbia.edu)
<br> <br>